version: "3.8"

services:
  mariadb:
    image: mariadb:latest
    container_name: thundersquad-db
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3316:3306"
    volumes:
      - mariadb-data:/var/lib/mysql

volumes:
  mariadb-data:
