version: "3.8"

services:
  mariadb:
    image: mariadb:latest
    container_name: thundersquad-db
    environment:
      MYSQL_ROOT_PASSWORD: r9oTSl2PhLbsXe
      MYSQL_DATABASE: thundersquad
      MYSQL_USER: thundersquad
      MYSQL_PASSWORD: T3lhzpwPLYvQq1
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql

volumes:
  mariadb-data:
